# Generated by Django 4.2.2 on 2023-06-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_worker_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Project Manager', 'Project Manager'), ('QA', 'QA'), ('Designer', 'Designer'), ('DevOps', 'DevOps'), ('HR', 'HR'), ('CEO', 'CEO')], max_length=63, unique=True),
        ),
    ]
