# Generated by Django 4.2.2 on 2023-06-17 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_alter_task_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['position'], 'verbose_name': 'worker', 'verbose_name_plural': 'workers'},
        ),
    ]
