# Generated by Django 4.2.2 on 2023-06-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_alter_worker_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['priority']},
        ),
    ]
