# Generated by Django 4.2.2 on 2023-06-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/workers_photo'),
        ),
    ]
