# Generated by Django 3.2.6 on 2023-07-04 20:15

from django.db import migrations, models
import task_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0011_alter_worker_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=task_manager.models.worker_image_file_path),
        ),
    ]
